version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: kaziconnect_db
      POSTGRES_USER: kaziconnect_user
      POSTGRES_PASSWORD: kaziconnect_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: